tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: SJEGOU_DB
      schema: dbt_dev
      warehouse: DBT
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: SJEGOU_DB
      schema: dbt_dev
      warehouse: DBT